name: build-os
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the OS image to build'
        required: true
        type: string
      base_release_name:
        description: 'The release name of the RPi OS base image (bullseye, bookworm)'
        required: true
        type: string
      base_image_variant:
        description: 'The name of the RPi OS base image variant (lite, desktop, or full)'
        required: true
        type: string
      base_release_date:
        description: 'The release date of the RPi OS base image'
        required: true
        type: string
      base_file_release_date:
        description: 'The release date of the RPi OS base image file, if different from the group release date'
        required: false
        type: string
      arch:
        description: 'The CPU architecture of the OS (armhf, arm64)'
        required: true
        type: string

jobs:
  build-os-image:
    name: Build image
    runs-on: ubuntu-24.04-arm
    env:
      KERNEL_VERSION: 6.1.21
      SETUP_USER: pi
    permissions:
      contents: read
      packages: write
      id-token: write
    timeout-minutes: 90
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # GET BASE IMAGE

      - name: Determine Raspberry Pi OS base image URL
        id: rpi-os-image
        run: |
          case '${{ inputs.base_release_name }}' in
            'bookworm')
              IMAGE_RELEASE_CHANNEL='raspios'
              ;;
            'bullseye')
              IMAGE_RELEASE_CHANNEL='raspios_oldstable'
              ;;
            *)
              echo "Unknown release name: ${{ inputs.base_release_name }}"
              exit 1
              ;;
          esac
          IMAGE_REPO_GROUP="$IMAGE_RELEASE_CHANNEL"
          if [[ "${{ inputs.base_image_variant }}" != "desktop" ]]; then
            IMAGE_REPO_GROUP="${IMAGE_REPO_GROUP}_${{ inputs.base_image_variant }}"
          fi
          IMAGE_REPO_GROUP="${IMAGE_REPO_GROUP}_${{ inputs.arch }}"
          if [[ -z "${{ inputs.base_file_release_date }}" ]]; then
            BASE_FILE_RELEASE_DATE="${{ inputs.base_release_date }}"
          else
            BASE_FILE_RELEASE_DATE="${{ inputs.base_file_release_date }}"
          fi
          IMAGE_FILENAME="$BASE_FILE_RELEASE_DATE-raspios-${{ inputs.base_release_name }}-${{ inputs.arch }}"
          if [[ "${{ inputs.base_image_variant }}" != "desktop" ]]; then
            IMAGE_FILENAME="${IMAGE_FILENAME}-${{ inputs.base_image_variant }}"
          fi
          IMAGE_FILENAME="${IMAGE_FILENAME}.img.xz"
          IMAGE_URL="https://downloads.raspberrypi.com/$IMAGE_REPO_GROUP/images/$IMAGE_REPO_GROUP-${{ inputs.base_release_date }}/$IMAGE_FILENAME"
          echo "RPi OS image filename: $IMAGE_FILENAME"
          echo "image_filename=$IMAGE_FILENAME" >> $GITHUB_OUTPUT
          echo "RPi OS image URL: $IMAGE_URL"
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Download and cache base image
        id: download-base
        uses: ethanjli/cached-download-action@v0.1.2
        with:
          url: ${{ steps.rpi-os-image.outputs.image_url }}
          destination: /tmp/${{ steps.rpi-os-image.outputs.image_filename }}

      - name: Decompress & grow base image
        id: expand-image
        uses: ethanjli/pigrow-action@v0.1.1
        with:
          image: ${{ steps.download-base.outputs.destination }}
          mode: to
          size: 16G

      # RUN OS SETUP SCRIPTS

      # Note: the following step isn't strictly necessary, but it's nice to separate the GitHub
      # Actions log outputs for setting up pinspawn-action for the first time from the logs for
      # the OS installation script
      - name: Install pinspawn-action dependencies
        uses: ethanjli/pinspawn-action@v0.1.4
        with:
          image: ${{ steps.expand-image.outputs.destination }}
          run: echo "Done!"

      - name: Run OS setup scripts in an unbooted container
        uses: ethanjli/pinspawn-action@v0.1.4
        with:
          image: ${{ steps.expand-image.outputs.destination }}
          user: ${{ env.SETUP_USER }}
          # Note: CAP_NET_ADMIN is needed for iptables, which is needed for Docker (at least in an
          # unbooted container). Setting the machine ID (and therefore hostname) to `raspberrypi`
          # resolves noisy (but harmless) error messages from sudo.
          args: >-
            --bind "$(pwd)":/run/os-setup
            --capability=CAP_NET_ADMIN
            --machine=raspberrypi
          run: |
            echo "Running setup scripts..."
            export DEBIAN_FRONTEND=noninteractive
            /run/os-setup/setup.sh
            echo "Done!"

      # UPLOAD OS IMAGE

      - name: Determine output image name
        env:
          TAG_PREFIX: "v"
        run: |
          # Determine the version for the image name
          if [[ -n "${{ github.event.pull_request.head.sha }}" ]]; then
            # We're in a pull request
            version="$(\
              printf "pr-%s-%.7s" \
                "${{ github.event.pull_request.number }}" \
                "${{ github.event.pull_request.head.sha }}" \
            )"
          elif [[ "${{ github.ref_type }}" == "tag" && "${{ github.ref }}" == refs/tags/$TAG_PREFIX* ]]; then
            version="${{ github.ref }}"
            version="v${version#"refs/tags/$TAG_PREFIX"}"
          else
            version="$(printf "%.7s" "${{ github.sha }}")"
          fi

          # Assemble the image name
          output_name="${{ inputs.name }}-$version"
          echo "OUTPUT_IMAGE_NAME=$output_name" >> $GITHUB_ENV

      - name: Shrink the OS image
        uses: ethanjli/pishrink-action@v0.1.3
        env:
          PISHRINK_XZ: -T0 ${{ github.ref_type == 'tag' && '-9' || '-1' }}
        with:
          image: ${{ steps.expand-image.outputs.destination }}
          destination: ${{ env.OUTPUT_IMAGE_NAME }}.img
          compress: xz
          compress-parallel: true

      - name: Upload image to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_IMAGE_NAME }}
          path: ${{ env.OUTPUT_IMAGE_NAME }}.img.xz
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
